collect_news_task:
  description: >
    Search for the latest finance-related news articles from reliable sources using the provided tools. Gather at least 50 articles that could be relevant to AI and finance.
  expected_output: >
    A list of 50 finance-related news articles with their URLs and publication dates.
  tools:
    - NewsAPITool
  agent: news_researcher


filter_ai_articles_task:
  description: >
    Filter the collected finance-related news articles to identify those relevant to AI. Discard irrelevant articles and retain only those with significant AI content.
  expected_output: >
    A filtered list of 20-30 articles that are directly relevant to AI and finance.
  tools: []
  agent: ai_filter


summarize_articles_task:
  description: >
    Summarize the filtered AI-related articles into concise news summaries following the given rules:
    - Headline should be short and crisp
    - No opinion should be added
    - Headline in sentence case
    - Word count less than 65 words
    - Article in past tense
    - Output only the headline and news article
  expected_output: >
    A JSON object containing 20-30 summarized news articles with the required fields: headlines, news_content, image_url, news_source_url, and article_date.
  tools:
    - SummarizationTool
  agent: summarizer

